include:
  - local: deployments/.gitlab/ci/build.gitlab-ci.yml
  - local: deployments/.gitlab/ci/release.gitlab-ci.yml
  - local: deployments/.gitlab/ci/test.gitlab-ci.yml

# Define stages that will be executed in the CI/CD pipeline
stages:
  - build
  - release
  - test 
default:
  image: docker-ro.laputa.veracode.io/policy/policy-cicd:latest
  # Define variables for reuse
variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: '/certs/client'
   # Define the name of the binary produced by the build process
  BINARY_NAME: "helloworld"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always