#include:
#  - local: deployments/.gitlab/ci/build.gitlab-ci.yml
#  - local: deployments/.gitlab/ci/release.gitlab-ci.yml
#  - local: deployments/.gitlab/ci/test.gitlab-ci.yml
#
## Define stages that will be executed in the CI/CD pipeline
#stages:
#  - build
#  - release
#  - test
#
## Define variables for reuse
#variables:
#  # Define the name of the binary produced by the build process
#  BINARY_NAME: "helloworld"

#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'push'
#      when: never
#    - when: always

include:
  - local: deployments/.gitlab/ci/build.gitlab-ci.yml
  - local: deployments/.gitlab/ci/release.gitlab-ci.yml
  - local: deployments/.gitlab/ci/test.gitlab-ci.yml
#
#stages:
#  - build
#  - release
#  - test
#
#variables:
#  BINARY_NAME: "helloworld"
#
#release-app:
#  stage: release
#  script:
#    - echo "Releasing app"
#    - exit 1  # This will cause the job to fail
#    # Add your release app script here
#  allow_failure: false
#
#release-brew-tap:
#  stage: release
#  script:
#    - echo "Releasing brew tap"
#    # Add your release brew tap script here
#  depends_on:
#    - release-app  # This job only runs if release-app succeeds
#testing-testing:
#    stage: test
#    script:
#      - echo "Next stage job"
#      # Add your next stage script here
#    when: always
#workflow:
#  rules:
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#      when: always
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#      when: always
#    - if: '$CI_PIPELINE_SOURCE == "push"'
#      allow_failure: true


# Release job
release-app:
  stage: release
  dependencies:
    - build  # Ensures build stage completes before release
  script:
    - echo "Releasing the app..."
    - # Your release app scripts here
  allow_failure: false  # Fail the job if the script exits with a non-zero status

# Release brew tap job
release-brew-tap:
  stage: release
  dependencies:
    - release-app  # Ensure this job runs after release-app
  script:
    - echo "Releasing brew tap..."
    - # Your release brew tap scripts here
  when: on_success  # Only runs if release-app succeeds

# Test job
test:
  stage: test
  script:
    - echo "Running tests..."
    - # Your test scripts here