# Define stages that will be executed in the CI/CD pipeline
stages:
  - build
  - release

# Define variables for reuse
variables:
  # Define the name of the binary produced by the build process
  BINARY_NAME: "helloworld"

# Define the build job
build:
  stage: build
  image: golang:latest  # Use the official Golang Docker image
  script:
    # Fetch dependencies
    - go mod download
    # Build the Go application
    - go build -o $BINARY_NAME ./cmd/server/main.go 

# Define the release job
release:
  stage: release
  image:
    name: goreleaser/goreleaser-cross:v1.21.5
    entrypoint: [""]
  services:
    - name: docker:dind
      alias: docker
  artifacts:
    paths:
      - out/
  only:
    - tags

  dependencies:
    - build
  script:
    # Run goreleaser for releasing the binary
    - goreleaser release --clean

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
