include:
  - local: deployments/.gitlab/ci/build.gitlab-ci.yml
  - local: deployments/.gitlab/ci/release.gitlab-ci.yml
  - local: deployments/.gitlab/ci/mac-test.gitlab-ci.yml

# Define stages that will be executed in the CI/CD pipeline
stages:
  - build
  - release
  - test 

# Define variables for reuse
variables:
  # Define the name of the binary produced by the build process
  BINARY_NAME: "helloworld"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always