#include:
#  - local: deployments/.gitlab/ci/build.gitlab-ci.yml
#  - local: deployments/.gitlab/ci/release.gitlab-ci.yml
#  - local: deployments/.gitlab/ci/test.gitlab-ci.yml
#
## Define stages that will be executed in the CI/CD pipeline
#stages:
#  - build
#  - release
#  - test
#
## Define variables for reuse
#variables:
#  # Define the name of the binary produced by the build process
#  BINARY_NAME: "helloworld"

#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'push'
#      when: never
#    - when: always

include:
  - local: deployments/.gitlab/ci/build.gitlab-ci.yml
  - local: deployments/.gitlab/ci/release.gitlab-ci.yml
  - local: deployments/.gitlab/ci/test.gitlab-ci.yml

stages:
  - build
  - release
  - test

variables:
  BINARY_NAME: "helloworld"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success

release_app:
  stage: release
  script:
    - echo "Releasing app"
    # Add your release app script here
  when: on_success

release_brew_tap:
  stage: release
  script:
    - echo "Releasing brew tap"
    # Add your release brew tap script here
  needs: ["release_app"]
  when: on_success
  rules:
    - when: on_success
      allow_failure: true

next_stage_job:
  stage: test
  script:
    - echo "Next stage job"
    # Add your next stage script here
  needs: ["release_app"]
  when: always
