version: 1
project_name: helloworld
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod vendor

builds:
  - main: ./cmd/server/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  gitlab:
    owner: gitlab.laputa.veracode.io/npm
    name: helloworld
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
checksum:
  name_template: "checksums.txt"
# .goreleaser.yaml
force_token: github

  # Homebrew tap
brews:
  - name: helloworld
    description: "You use the Veracode CLI to perform various actions for testing the security of your applications."
    homepage: "https://www.veracode.com"
    url_template: "https://tools.veracode.com/veracode-cli/veracode-cli_{{ replace .Tag \"v\" \"\"}}_{{ if eq .Os \"darwin\" }}macosx_arm64.tar.gz{{ else if eq .Os \"linux\" }}linux_x86.tar.gz{{ end }}"
    license: "MIT"
    repository:
      owner: "{{ .Env.OWNER }}"
      name: "{{ .Env.HOMEBREW_REPO }}"
      token: "{{ .Env.GITHUB_TOKEN }}"
      git:
        url: 'git@github.com:Noush-012/homebrew-tools.git'
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    install: |
      bin.install "helloworld"
    test: |
      system "#{bin}/helloworld --version"
