version: 1
project_name: helloworld
gitlab_urls:
  api: https://gitlab.laputa.helloworld.io/api/v4
  download: https://gitlab.laputa.helloworld.io
  skip_tls_verify: false
  use_package_registry: false
env:
  - GITLAB_TOKEN={{ .Env.GITLAB_TOKEN }}
force_token: gitlab
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod vendor

builds:
  - main: ./cmd/server/main.go
    binary: "helloworld"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macosx
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      
brews:
  - name: helloworld
    description: "You use the helloworld CLI to perform various actions for testing the security of your applications."
    homepage: "https://www.helloworld.com"
    license: "MIT"
    url_template: "https://tools.helloworld.com/helloworld-cli/helloworld-cli_{{ replace .Tag \"v\" \"\"}}_{{ if eq .Os \"darwin\" }}macosx_arm64.tar.gz{{ else if eq .Os \"linux\" }}linux_x86.tar.gz{{ end }}"
    repository:
      owner: Noush-012
      name: homebrew-tools
    skip_upload: true
    directory: Formula
    install: |
      bin.install "helloworld"
    test: |
      system "#{bin}/helloworld --version"

checksum:
  name_template: "checksums.txt"