  # Homebrew tap
version: 1
project_name: helloworld

builds:
  - main: ./cmd/server/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

universal_binaries:
  - replace: true
force_token: github
release:
 github:
 skip_upload: true

brews:
  - name: helloworld
    description: "You use the Veracode CLI to perform various actions for testing the security of your applications."
    homepage: "https://www.veracode.com"
    url_template: "https://tools.veracode.com/veracode-cli/veracode-cli_{{ replace .Tag \"v\" \"\"}}_{{ if eq .Os \"darwin\" }}macosx_arm64.tar.gz{{ else if eq .Os \"linux\" }}linux_x86.tar.gz{{ end }}"
    license: "MIT"
    repository:
      owner: "{{ .Env.GITHUB_OWNER }}"
      name: "{{ .Env.HOMEBREW_REPO }}"
      token: "{{ .Env.GITHUB_TOKEN }}"
      branch: main
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    install: |
      bin.install "helloworld"
    test: |
      system "#{bin}/helloworld --version"

checksum:
  name_template: "checksums.txt"