# Define the build job
build:
  stage: build
  image: 
    name: golang:latest  # Use the official Golang Docker image
    entrypoint: [""]
  script:
    # Fetch dependencies
    - go mod download
    - echo $CI_COMMIT_TAG
    # Build the Go application
    - go build -o $BINARY_NAME ./cmd/server/main.go
  artifacts:
    paths:
      - bin/myapp   
  rules:
    - when: always