# Define the build job
build:
  stage: build
  image: 
    name: golang:latest  # Use the official Golang Docker image
    entrypoint: [""]
  script:
    # Fetch dependencies
    # - go mod download
    # Build the Go application
    # - go build -o $BINARY_NAME ./cmd/server/main.go
      - echo "$BINARY_NAME building....."
  artifacts:
    paths:
      - bin/myapp   
  rules:
    - when: always