brew-test-veracode:
  stage: test
  needs: ["release-brew-tap"]
  image:
    name: sickcodes/docker-osx:naked-auto
    entrypoint: [""]
  only:
    - tags
  when: on_success 
  before_script:
    - uname -a
    - sw_vers
    - sysctl -n machdep.cpu.brand_string
  script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"