brew-test-veracode:
  stage: test
  needs: ["release-brew-tap"]
  image: ubuntu:latest
  only:
    - tags
  when: on_success
  before_script:
    - apt-get update
    - apt-get install -y build-essential curl file git
    - mkdir -p /home/linuxbrew/.linuxbrew && curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
    - echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /root/.bashrc
    - eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    - brew update
    - brew --version
  script:
    - brew tap foocode123/tools
    - brew install foocode-cli
    - veracode version
    - veracode help