brew-test-veracode:
  stage: test
  needs: ["release-brew-tap"]
  image:
    name: sickcodes/docker-osx:naked-auto
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG 
      when: always
  when: on_success 
  before_script:
    - uname -a
    - sw_vers
    - sysctl -n machdep.cpu.brand_string
  script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   
